### ISSUE TITLE
data.mat

### ISSUE THREAD

**Issue by Feesics** [zhangyuygss/HSI_Classification#1]
Thanks for your code, but I have a problem about the file  named "data.mat", I want to know how to generate it ? And  the number of train set and test set are added not equal 10366, what's the means of "10366"?

**Comment by zhangyuygss** [comment]
The [aviris_data_generation.m](https://github.com/zhangyuygss/HSI_Classification/blob/master/aviris_data_generation.m) is for generating "data.mat" file. 
Where is the number "10366"?

**Comment by Feesics** [comment]
Get it! Thanks!
